---
ID: "7839bc36-e4c2-43ec-aef3-847fb55f7338"
Parent: "f153d3f3-9e0c-4802-8a0c-7f1394eed8d5"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/omnia-sugmea-ready/omnia-sugmea-ready/Presentation/Headless Variants/LinkList/Default"
BranchID: "70519928-c595-4b2b-bb35-75022feecc4c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{25F1A8E5-EB4C-4202-A9F7-A97DB52DA9AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "df77d8bc-39f3-4fdd-af00-b4f9f9625f62"
